Cert auth
NTIA/scos-sensor pull request #223
Opened 2023-01-30 19:38 UTC by jhazentia

Browsable api timeout doesn't work, always logged in

2024-01-05 19:37 UTC, dboulware requested changes
This looks good. Only some minor comments to address.

2024-01-08 15:34 UTC, jhazentia commented on README.md
> +ssl_client_certificate /etc/ssl/certs/ca.crt;
Per our discussion, we decided to leave as one template. Ansible can do string replacement.

2024-01-08 16:27 UTC, jhazentia commented on src/authentication/auth.py
> +                raise exceptions.AuthenticationFailed("No matching username found!")
Fixed in 3590675

2024-01-08 16:57 UTC, jhazentia commented on scripts/create_superuser.py
> +            add_user(additional_user_name, additional_user_password)
Fixed in 3590675

2024-01-08 19:53 UTC, jhazentia commented on README.md
> +The Nginx web server is configured by default to require client certificates (mutual
I made some changes. Please check if new version is good (commit e9b2f30)

2024-01-08 19:54 UTC, jhazentia commented on nginx/conf.template
> +        # if ($ssl_client_verify != SUCCESS) {
Tested and confirmed that this does not seem to make any difference. Removed in e9b2f30

2024-01-08 19:56 UTC, jhazentia commented on README.md
> +The Nginx web server is configured by default to require client certificates (mutual
Removed `ssl_ocsp on ` setting from README Nginx configuration text blocks. This has not been tested and unsure if additional settings required.

2024-01-16 14:51 UTC, dboulware requested changes
Looks good. Just one minor request. Add to the log message the user that could not be found when unable to find the user.

2024-01-17 16:44 UTC, dboulware approved these changes

2024-01-17 16:45 UTC, dboulware requested changes
Looks good. Can you resolve the conflicts?

2024-01-17 18:05 UTC, jhazentia commented
> Looks good. Can you resolve the conflicts?

Done

2024-01-18 17:39 UTC, dboulware approved these changes

2024-01-18 17:39 UTC, merged